### ISSUE TITLE
Strange concurrency issue during spec run

### ISSUE THREAD

**Issue by jsvd** [logstash-plugins/logstash-input-relp#8]
```
Failures:

  1) LogStash::Outputs::S3 when rotating the temporary file doesn't skip events if using the time_file option
     Failure/Error: Unable to find matching line from backtrace
     ConcurrencyError:
       Detected invalid hash contents due to unsynchronized modifications with concurrent users
     # org/jruby/RubyHash.java:1511:in `keys'
     # /Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-relp-0.1.4/lib/logstash/util/relp.rb:294:in `initialize'
     # org/jruby/RubyKernel.java:1507:in `loop'
     # /Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-relp-0.1.4/lib/logstash/util/relp.rb:292:in `initialize'
```
